version: '3.4'

services:
  onlinestore.api.customers:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6002:80"

  onlinestore.api.orders:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6003:80"


  onlinestore.api.products:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6001:80"


  onlinestore.api.search:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - services__Products=http://onlinestore.api.products
      - services__Customers=http://onlinestore.api.customers
      - services__Orders=http://onlinestore.api.orders
    ports:
      - "6004:80"

